---
title: "COLORADO part 2"
author: "Jiahao Liu"
date: "2023-04-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
coal_cons <- read.csv('MER_T06_02.csv')
gas_cons_res <- read.csv('Colorado_Natural_Gas_Residential_Consumption.csv')
gas_cons_com <- read.csv('Natural_Gas_Deliveries_to_Commercial_Consumers_(Including_Vehicle_Fuel_through_1996)_in_Colorado.csv')
gas_cons_ind <- read.csv('Colorado_Natural_Gas_Industrial_Consumption.csv')
```

```{r}
gas_cons_ind <- c(gas_cons_ind[5:269,])
gas_cons_ind <- data.frame(gas_cons_ind)
gas_cons_ind <- as.numeric(gas_cons_ind$gas_cons_ind)
gas_cons_ind <- data.frame(gas_cons_ind)
names(gas_cons_ind) <- 'Gas_cons_industry'
```

```{r}
gas_cons_com <- c(gas_cons_com[5:269,])
gas_cons_com <- data.frame(gas_cons_com)
gas_cons_com <- as.numeric(gas_cons_com$gas_cons_com)
gas_cons_com <- data.frame(gas_cons_com)
names(gas_cons_com) <- 'Gas_cons_commercial'
```

```{r}
gas_cons_res <- c(gas_cons_res[5:269,])
gas_cons_res <- data.frame(gas_cons_res)
gas_cons_res <- as.numeric(gas_cons_res$gas_cons_res)
gas_cons_res <- data.frame(gas_cons_res)
names(gas_cons_res) <- 'Gas_cons_residential'
```

```{r}
unique(coal_cons$Description)
coal_cons_com <- coal_cons %>% filter(Description == 'Coal Consumed by the Commercial Sector, Total')
coal_cons_ind <- coal_cons %>% filter(Description == 'Coal Consumed by the Industrial Sector, Total')
coal_cons_electp <- coal_cons %>% filter(Description == 'Coal Consumed by the Electric Power Sector')

coal_cons_com <- coal_cons_com[389:675,]
coal_cons_com <- coal_cons_com[-c(13,26,39,52,65,78,91,104,117,130,143,156,169,182,195,208,221,234,247,260,273,286),]
coal_cons_com$Value <- as.numeric(coal_cons_com$Value)
coal_cons_ind <- coal_cons_ind[389:675,]
coal_cons_ind <- coal_cons_ind[-c(13,26,39,52,65,78,91,104,117,130,143,156,169,182,195,208,221,234,247,260,273,286),]
coal_cons_ind$Value <- as.numeric(coal_cons_ind$Value)
coal_cons_electp <- coal_cons_electp[389:675,]
coal_cons_electp <- coal_cons_electp[-c(13,26,39,52,65,78,91,104,117,130,143,156,169,182,195,208,221,234,247,260,273,286),]
coal_cons_electp$Value <- as.numeric(coal_cons_electp$Value)
```

